#ifndef MBEDTLS_CONFIG_FTEL_CAMERA_H
#define MBEDTLS_CONFIG_FTEL_CAMERA_H

#define MBEDTLS_HAVE_TIME
#define MBEDTLS_HAVE_TIME_DATE
#define MBEDTLS_PLATFORM_C
#define MBEDTLS_PLATFORM_MEMORY
#define MBEDTLS_FS_IO

#define MBEDTLS_PEM_PARSE_C
#define MBEDTLS_BASE64_C

#define MBEDTLS_SSL_IN_CONTENT_LEN              8192
#define MBEDTLS_SSL_OUT_CONTENT_LEN             2048
#define MBEDTLS_SSL_TLS_C
#define MBEDTLS_SSL_CLI_C
#define MBEDTLS_ERROR_C
#define MBEDTLS_SSL_PROTO_TLS1_2
#define MBEDTLS_SSL_KEEP_PEER_CERTIFICATE



#define MBEDTLS_AES_C
#define MBEDTLS_GCM_C
#define MBEDTLS_CIPHER_C
#define MBEDTLS_SHA256_C
#define MBEDTLS_SHA1_C
#define MBEDTLS_MD_C
#define MBEDTLS_CTR_DRBG_C
#define MBEDTLS_ENTROPY_C


#define MBEDTLS_RSA_C
#define MBEDTLS_PKCS1_V15
#define MBEDTLS_BIGNUM_C
#define MBEDTLS_OID_C
#define MBEDTLS_ASN1_PARSE_C
#define MBEDTLS_PK_C
#define MBEDTLS_PK_PARSE_C
#define MBEDTLS_X509_USE_C
#define MBEDTLS_X509_CRT_PARSE_C
#define MBEDTLS_KEY_EXCHANGE_RSA_ENABLED

// #define MBEDTLS_USE_PSA_CRYPTO
// #define MBEDTLS_PSA_CRYPTO_C
// #define MBEDTLS_PSA_CRYPTO_STORAGE_C

#undef MBEDTLS_SSL_PROTO_SSL3
#undef MBEDTLS_SSL_PROTO_TLS1_0
#undef MBEDTLS_SSL_PROTO_TLS1_1

#endif /* MBEDTLS_CONFIG_FTEL_CAMERA_H */